public static class StartupNotice
{
	public const string ALL_MANAGERS_STARTED = "ALL_MANAGERS_STARTED";
	public const string MANAGERS_PROGRESS = "MANAGERS_PROGRESS";

	public const string ALL_CONTROLLERS_STARTED = "ALL_CONTROLLERS_STARTED";
	public const string CONTROLLERS_PROGRESS = "CONTROLLERS_PROGRESS";

	public const string PLAYER_MANAGER_STARTING = "PLAYER_MANAGER_STARTING";
	public const string DATA_MANAGER_STARTING = "DATA_MANAGER_STARTING";
	public const string GAME_MANAGER_STARTING = "GAME_MANAGER_STARTING";
	public const string UI_MANAGER_STARTING = "UI_MANAGER_STARTING";
	public const string SETINGS_MANAGER_STARTING = "SETINGS_MANAGER_STARTING";

	public const string PLAYER_MANAGER_STARTED = "PLAYER_MANAGER_STARTED";
	public const string DATA_MANAGER_STARTED = "DATA_MANAGER_STARTED";
	public const string GAME_MANAGER_STARTED = "GAME_MANAGER_STARTED";
	public const string UI_MANAGER_STARTED = "UI_MANAGER_STARTED";
	public const string SETINGS_MANAGER_STARTED = "SETINGS_MANAGER_STARTED";

	public const string CURRENCY_CONTROLLER_STARTED = "CURRENCY_CONTROLLER_STARTED";
	public const string STOCK_EXCHANGE_CONTROLLER_STARTED = "STOCK_EXCHANGE_CONTROLLER_STARTED";

	public const string PRIMARY_PRICES_GENERATION = "PRIMARY_PRICES_GENERATION";

	public const string GAME_STARTED = "STARTUP_NOTICE_" + "GAME_STARTED";
}